export const ON_GET_SHORT_URL_REQUESTED = 'ON_GET_SHORT_URL_REQUESTED'
export const ON_GET_SHORT_URL_SUCCEEDED = 'ON_GET_SHORT_URL_SUCCEEDED'
export const ON_GET_SHORT_URL_FAILED = 'ON_GET_SHORT_URL_FAILED'

export default {
    ON_GET_SHORT_URL_REQUESTED,
    ON_GET_SHORT_URL_SUCCEEDED,
    ON_GET_SHORT_URL_FAILED,
}