/*
** @file: caseHub
** @author: huanghaolei
** @date: 2019-05-20
*/
export const GET_GOOD_POST_CONTENT_REQUESTED = 'GET_GOOD_POST_CONTENT_REQUESTED'
export const GET_GOOD_POST_CONTENT_SUCCEEDED = 'GET_GOOD_POST_CONTENT_SUCCEEDED'
export const GET_GOOD_POST_CONTENT_FAILED = 'GET_GOOD_POST_CONTENT_FAILED'
export const GET_WX_LOGIN_URL_REQUESTED = 'GET_WX_LOGIN_URL_REQUESTED'
export const GET_WX_LOGIN_URL_SUCCEEDED = 'GET_WX_LOGIN_URL_SUCCEEDED'
export const GET_WX_LOGIN_URL_FAILED = 'GET_WX_LOGIN_URL_FAILED'
export const GET_USER_INFO_IN_WECHAT_REQUESTED = 'GET_USER_INFO_IN_WECHAT_REQUESTED'
export const GET_USER_INFO_IN_WECHAT_SUCCEEDED = 'GET_USER_INFO_IN_WECHAT_SUCCEEDED'
export const GET_USER_INFO_IN_WECHAT_FAILED = 'GET_USER_INFO_IN_WECHAT_FAILED'
export const ON_CLEAR_CONTENT_DATA  = 'ON_CLEAR_CONTENT_DATA'
export const ON_GET_WX_JS_SIGN_REQUESTED = 'ON_GET_WX_JS_SIGN_REQUESTED'
export const ON_GET_WX_JS_SIGN_SUCCEEDED = 'ON_GET_WX_JS_SIGN_SUCCEEDED'
export const ON_GET_WX_JS_SIGN_FAILED = 'ON_GET_WX_JS_SIGN_FAILED'

export const ON_ADD_WEIXIN_READ_CORD_REQUESTED = 'ON_ADD_WEIXIN_READ_CORD_REQUESTED'
export const ON_ADD_WEIXIN_READ_CORD_SUCCEEDED = 'ON_ADD_WEIXIN_READ_CORD_SUCCEEDED'
export const ON_ADD_WEIXIN_READ_CORD_FAILED = 'ON_ADD_WEIXIN_READ_CORD_FAILED'
export const ON_UPDATE_FORWARD_CNT_REQUESTED = 'ON_UPDATE_FORWARD_CNT_REQUESTED'
export const ON_UPDATE_FORWARD_CNT_FAILED = 'ON_UPDATE_FORWARD_CNT_FAILED'

export default {
    GET_GOOD_POST_CONTENT_REQUESTED,
    GET_GOOD_POST_CONTENT_SUCCEEDED,
    GET_GOOD_POST_CONTENT_FAILED,
    GET_WX_LOGIN_URL_REQUESTED,
    GET_WX_LOGIN_URL_SUCCEEDED,
    GET_WX_LOGIN_URL_FAILED,
    GET_USER_INFO_IN_WECHAT_REQUESTED,
    GET_USER_INFO_IN_WECHAT_SUCCEEDED,
    GET_USER_INFO_IN_WECHAT_FAILED,
    ON_CLEAR_CONTENT_DATA,
    ON_GET_WX_JS_SIGN_REQUESTED,
    ON_GET_WX_JS_SIGN_SUCCEEDED,
    ON_GET_WX_JS_SIGN_FAILED,
    ON_ADD_WEIXIN_READ_CORD_REQUESTED,
    ON_ADD_WEIXIN_READ_CORD_SUCCEEDED,
    ON_ADD_WEIXIN_READ_CORD_FAILED,
    ON_UPDATE_FORWARD_CNT_REQUESTED,
    ON_UPDATE_FORWARD_CNT_FAILED,
}