//获取专业信息
export const GET_MAJOR_INFO_REQUESTED = 'GET_MAJOR_INFO_REQUESTED';
export const GET_MAJOR_INFO_SUCCEEDED = 'GET_MAJOR_INFO_SUCCEEDED';
export const GET_MAJOR_INFO_FAILED = 'GET_MAJOR_INFO_FAILED';

//招生简章
export const GET_SCHOOL_INTRODUCTION_REQUESTED = 'GET_SCHOOL_INTRODUCTION_REQUESTED';
export const GET_SCHOOL_INTRODUCTION_SUCCEEDED = 'GET_SCHOOL_INTRODUCTION_SUCCEEDED';
export const GET_SCHOOL_INTRODUCTION_FAILED = 'GET_SCHOOL_INTRODUCTION_FAILED';

//全部考试科目页
export const GET_ALL_COURSE_LIST_REQUESTED = 'GET_ALL_COURSE_LIST_REQUESTED';
export const GET_ALL_COURSE_LIST_SUCCEEDED = 'GET_ALL_COURSE_LIST_SUCCEEDED';
export const GET_ALL_COURSE_LIST_FAILED = 'GET_ALL_COURSE_LIST_FAILED';

//分页获取帖子数据
export const GET_POST_BY_MAJORID_REQUESTED = 'GET_POST_BY_MAJORID_REQUESTED';
export const GET_POST_BY_MAJORID_SUCCEEDED = 'GET_POST_BY_MAJORID_SUCCEEDED';
export const GET_POST_BY_MAJORID_FAILED = 'GET_POST_BY_MAJORID_FAILED';

export default {
    GET_MAJOR_INFO_REQUESTED,
    GET_MAJOR_INFO_SUCCEEDED,
    GET_MAJOR_INFO_FAILED,

    GET_SCHOOL_INTRODUCTION_REQUESTED,
    GET_SCHOOL_INTRODUCTION_SUCCEEDED,
    GET_SCHOOL_INTRODUCTION_FAILED,

    GET_ALL_COURSE_LIST_REQUESTED,
    GET_ALL_COURSE_LIST_SUCCEEDED,
    GET_ALL_COURSE_LIST_FAILED,

    GET_POST_BY_MAJORID_REQUESTED,
    GET_POST_BY_MAJORID_SUCCEEDED,
    GET_POST_BY_MAJORID_FAILED,
}
