export const VIDEO_LIST_REQUESTED = 'VIDEO_LIST_REQUESTED'
export const VIDEO_LIST_SUCCEEDED = 'VIDEO_LIST_SUCCEEDED'
export const VIDEO_LIST_FAILED = 'VIDEO_LIST_FAILED'

export const RECORD_WATCH_REQUESTED = 'RECORD_WATCH_REQUESTED'
export const RECORD_WATCH_SUCCEEDED = 'RECORD_WATCH_SUCCEEDED'
export const RECORD_WATCH_FAILED = 'RECORD_WATCH_FAILED'

export default {
    VIDEO_LIST_REQUESTED,
    VIDEO_LIST_SUCCEEDED,
    VIDEO_LIST_FAILED,
    RECORD_WATCH_REQUESTED,
    RECORD_WATCH_SUCCEEDED,
    RECORD_WATCH_FAILED,
}