/*
 * @Author: litingwei
 * @Date: 2019-09-17 10:58:03
 * @LastEditTime: 2019-09-19 10:56:26
 * @LastEditors: litingwei
 */
export const GET_USER_PROFILE_REQUESTED = 'EXAMINE_GET_USER_PROFILE_REQUESTED'
export const GET_USER_PROFILE_SUCCEEDED = 'EXAMINE_GET_USER_PROFILE_SUCCEEDED'
export const GET_USER_PROFILE_FAILED = 'EXAMINE_GET_USER_PROFILE_FAILED'
export const QUERY_TAG_REQUESTED = 'EXAMINE_QUERY_TAG_REQUESTED'
export const QUERY_TAG_SUCCEEDED = 'EXAMINE_QUERY_TAG_SUCCEEDED'
export const QUERY_TAG_FAILED = 'EXAMINE_QUERY_TAG_FAILED'
export const UPDATE_TAG_INFO_REQUESTED = 'EXAMINE_UPDATE_TAG_INFO_REQUESTED'
export const UPDATE_TAG_INFO_SUCCEEDED = 'EXAMINE_UPDATE_TAG_INFO_SUCCEEDED'
export const UPDATE_TAG_INFO_FAILED = 'EXAMINE_UPDATE_TAG_INFO_FAILED'
export const GET_MY_POST_LIST_REQUESTED = 'EXAMINE_GET_MY_POST_LIST_REQUESTED'
export const GET_MY_POST_LIST_SUCCEEDED = 'EXAMINE_GET_MY_POST_LIST_SUCCEEDED'
export const GET_MY_POST_LIST_FAILED = 'EXAMINE_GET_MY_POST_LIST_FAILED'

export const ON_RESET_PERSONAL_PROFILE_STORE = 'EXAMINE_ON_RESET_PERSONAL_PROFILE_STORE'

export const SET_INVATATION_SHIELD_REQUESTED = 'EXAMINE_SET_INVATATION_SHIELD_REQUESTED'
export const SET_INVATATION_SHIELD_SUCCESSED = 'EXAMINE_SET_INVATATION_SHIELD_SUCCESSED'
export const SET_INVATATION_SHIELD_FAILED = 'EXAMINE_SET_INVATATION_SHIELD_FAILED'

export const GET_USERINFO_BY_TOKEN_REQUESTED = 'EXAMINE_GET_USERINFO_BY_TOKEN_REQUESTED'
export const GET_USERINFO_BY_TOKEN_SUCCESSED = 'EXAMINE_GET_USERINFO_BY_TOKEN_SUCCESSED'
export const GET_USERINFO_BY_TOKEN_FAILED = 'EXAMINE_GET_USERINFO_BY_TOKEN_FAILED'

export const DO_BATCH_AUDIT_FOR_POST_REQUESTED = 'EXAMINE_DO_BATCH_AUDIT_FOR_POST_REQUESTED'
export const DO_BATCH_AUDIT_FOR_POST_SUCCESSED = 'EXAMINE_DO_BATCH_AUDIT_FOR_POST_SUCCESSED'
export const DO_BATCH_AUDIT_FOR_POST_FAILED = 'EXAMINE_DO_BATCH_AUDIT_FOR_POST_FAILED'

export default {
    GET_USER_PROFILE_REQUESTED,
    GET_USER_PROFILE_SUCCEEDED,
    GET_USER_PROFILE_FAILED,
    QUERY_TAG_REQUESTED,
    QUERY_TAG_SUCCEEDED,
    QUERY_TAG_FAILED,
    UPDATE_TAG_INFO_REQUESTED,
    UPDATE_TAG_INFO_SUCCEEDED,
    UPDATE_TAG_INFO_FAILED,
    GET_MY_POST_LIST_REQUESTED,
    GET_MY_POST_LIST_SUCCEEDED,
    GET_MY_POST_LIST_FAILED,
    ON_RESET_PERSONAL_PROFILE_STORE,
    SET_INVATATION_SHIELD_REQUESTED,
    SET_INVATATION_SHIELD_SUCCESSED,
    SET_INVATATION_SHIELD_FAILED,
    GET_USERINFO_BY_TOKEN_REQUESTED,
    GET_USERINFO_BY_TOKEN_SUCCESSED,
    GET_USERINFO_BY_TOKEN_FAILED,
    DO_BATCH_AUDIT_FOR_POST_REQUESTED,
    DO_BATCH_AUDIT_FOR_POST_SUCCESSED,
    DO_BATCH_AUDIT_FOR_POST_FAILED,
}
