export const ON_GET_STU_TASKS_REQUESTED = 'ON_GET_STU_TASKS_REQUESTED'
export const ON_GET_STU_TASKS_SUCCEEDED = 'ON_GET_STU_TASKS_SUCCEEDED'
export const ON_GET_STU_TASKS_FAILED = 'ON_GET_STU_TASKS_FAILED'

export const GET_TIKU_INFO_REQUESTED = 'GET_TIKU_INFO_REQUESTED'
export const GET_TIKU_INFO_SUCCEEDED = 'GET_TIKU_INFO_SUCCEEDED'
export const GET_TIKU_INFO_FAILED = 'GET_TIKU_INFO_FAILED'

export const DO_TASK_REQUESTED = 'DO_TASK_REQUESTED'
export const DO_TASK_SUCCEEDED = 'DO_TASK_SUCCEEDED'
export const DO_TASK_FAILED = 'DO_TASK_FAILED'

export const GET_ACTIVITY_INFO_REQUESTED = 'examTask/GET_ACTIVITY_INFO_REQUESTED'
export const GET_ACTIVITY_INFO_SUCCEEDED = 'examTask/GET_ACTIVITY_INFO_SUCCEEDED'
export const GET_ACTIVITY_INFO_FAILED = 'examTask/GET_ACTIVITY_INFO_FAILED'

export const GET_STU_CARDS_REQUESTED = 'examTask/GET_STU_CARDS_REQUESTED'
export const GET_STU_CARDS_SUCCEEDED = 'examTask/GET_STU_CARDS_SUCCEEDED'
export const GET_STU_CARDS_FAILED = 'examTask/GET_STU_CARDS_FAILED'

export const GET_STU_CARDS_BY_TAG_REQUESTED = 'examTask/GET_STU_CARDS_BY_TAG_REQUESTED'
export const GET_STU_CARDS_BY_TAG_SUCCEEDED = 'examTask/GET_STU_CARDS_BY_TAG_SUCCEEDED'
export const GET_STU_CARDS_BY_TAG_FAILED = 'examTask/GET_STU_CARDS_BY_TAG_FAILED'

export const GET_CARD_REQUESTED = 'examTask/GET_CARD_REQUESTED'
export const GET_CARD_SUCCEEDED = 'examTask/GET_CARD_SUCCEEDED'
export const GET_CARD_FAILED = 'examTask/GET_CARD_FAILED'

export const GET_CARD_CNT_REQUESTED = 'examTask/GET_CARD_CNT_REQUESTED'
export const GET_CARD_CNT_SUCCEEDED = 'examTask/GET_CARD_CNT_SUCCEEDED'
export const GET_CARD_CNT_FAILED = 'examTask/GET_CARD_CNT_FAILED'

export const SYNTHESIZE_REQUESTED = 'examTask/SYNTHESIZE_REQUESTED'
export const SYNTHESIZE_SUCCEEDED = 'examTask/SYNTHESIZE_SUCCEEDED'
export const SYNTHESIZE_FAILED = 'examTask/SYNTHESIZE_FAILED'

export const GET_RESULT_REQUESTED = 'examTask/GET_RESULT_REQUESTED'
export const GET_RESULT_SUCCEEDED = 'examTask/GET_RESULT_SUCCEEDED'
export const GET_RESULT_FAILED = 'examTask/GET_RESULT_FAILED'

export const GET_WEIXIN_ACCOUNT_REQUESTED = 'examTask/GET_WEIXIN_ACCOUNT_REQUESTED'
export const GET_WEIXIN_ACCOUNT_SUCCEEDED = 'examTask/GET_WEIXIN_ACCOUNT_SUCCEEDED'
export const GET_WEIXIN_ACCOUNT_FAILED = 'examTask/GET_WEIXIN_ACCOUNT_FAILED'

export const BIND_WECHAT_REQUESTED = 'examTask/BIND_WECHAT_REQUESTED'
export const BIND_WECHAT_SUCCEEDED = 'examTask/BIND_WECHAT_SUCCEEDED'
export const BIND_WECHAT_FAILED = 'examTask/BIND_WECHAT_FAILED'

export const WITHDRAW_REQUESTED = 'examTask/WITHDRAW_REQUESTED'
export const WITHDRAW_SUCCEEDED = 'examTask/WITHDRAW_SUCCEEDED'
export const WITHDRAW_FAILED = 'examTask/WITHDRAW_FAILED'

export default {
    ON_GET_STU_TASKS_REQUESTED,
    ON_GET_STU_TASKS_SUCCEEDED,
    ON_GET_STU_TASKS_FAILED,

    GET_TIKU_INFO_REQUESTED,
    GET_TIKU_INFO_SUCCEEDED,
    GET_TIKU_INFO_FAILED,

    DO_TASK_REQUESTED,
    DO_TASK_SUCCEEDED,
    DO_TASK_FAILED,

    GET_ACTIVITY_INFO_REQUESTED,
    GET_ACTIVITY_INFO_SUCCEEDED,
    GET_ACTIVITY_INFO_FAILED,

    GET_STU_CARDS_REQUESTED,
    GET_STU_CARDS_SUCCEEDED,
    GET_STU_CARDS_FAILED,

    GET_STU_CARDS_BY_TAG_REQUESTED,
    GET_STU_CARDS_BY_TAG_SUCCEEDED,
    GET_STU_CARDS_BY_TAG_FAILED,

    GET_CARD_REQUESTED,
    GET_CARD_SUCCEEDED,
    GET_CARD_FAILED,

    GET_CARD_CNT_REQUESTED,
    GET_CARD_CNT_SUCCEEDED,
    GET_CARD_CNT_FAILED,

    SYNTHESIZE_REQUESTED,
    SYNTHESIZE_SUCCEEDED,
    SYNTHESIZE_FAILED,

    GET_RESULT_REQUESTED,
    GET_RESULT_SUCCEEDED,
    GET_RESULT_FAILED,

    GET_WEIXIN_ACCOUNT_REQUESTED,
    GET_WEIXIN_ACCOUNT_SUCCEEDED,
    GET_WEIXIN_ACCOUNT_FAILED,

    BIND_WECHAT_REQUESTED,
    BIND_WECHAT_SUCCEEDED,
    BIND_WECHAT_FAILED,

    WITHDRAW_REQUESTED,
    WITHDRAW_SUCCEEDED,
    WITHDRAW_FAILED,
}