//根据话题获取帖子列表
export const GET_POST_BY_TOPIC_REQUESTED = 'GET_POST_BY_TOPIC_REQUESTED';
export const GET_POST_BY_TOPIC_SUCCEEDED = 'GET_POST_BY_TOPIC_SUCCEEDED';
export const GET_POST_BY_TOPIC_FAILED = 'GET_POST_BY_TOPIC_FAILED';

export default {
    GET_POST_BY_TOPIC_REQUESTED,
    GET_POST_BY_TOPIC_SUCCEEDED,
    GET_POST_BY_TOPIC_FAILED
}
