export const GET_GROUP_RANK_DETAIL_REQUESTED = 'GET_GROUP_RANK_DETAIL_REQUESTED';
export const GET_GROUP_RANK_DETAIL_SUCCEEDED = 'GET_GROUP_RANK_DETAIL_SUCCEEDED';
export const GET_GROUP_RANK_DETAIL_FAILED = 'GET_GROUP_RANK_DETAIL_FAILED';

export default {
    GET_GROUP_RANK_DETAIL_REQUESTED,
    GET_GROUP_RANK_DETAIL_SUCCEEDED,
    GET_GROUP_RANK_DETAIL_FAILED,
}
