//根据群发批次获取详情
export const GET_GROUP_BATCH_REQUESTED = 'GET_GROUP_BATCH_REQUESTED';
export const GET_GROUP_BATCH_SUCCEEDED = 'GET_GROUP_BATCH_SUCCEEDED';
export const GET_GROUP_BATCH_FAILED = 'GET_GROUP_BATCH_FAILED';

export const GET_TEACHER_MSG_DETAIL_REQUESTED = 'GET_TEACHER_MSG_DETAIL_REQUESTED';
export const GET_TEACHER_MSG_DETAIL_SUCCEEDED = 'GET_TEACHER_MSG_DETAIL_SUCCEEDED';
export const GET_TEACHER_MSG_DETAIL_FAILED = 'GET_TEACHER_MSG_DETAIL_FAILED'

export const GET_SYS_MSG_DETAIL_BY_SYS_MSG_ID_REQUESTED = 'GET_SYS_MSG_DETAIL_BY_SYS_MSG_ID_REQUESTED';
export const GET_SYS_MSG_DETAIL_BY_SYS_MSG_ID_SUCCEEDED = 'GET_SYS_MSG_DETAIL_BY_SYS_MSG_ID_SUCCEEDED';
export const GET_SYS_MSG_DETAIL_BY_SYS_MSG_ID_FAILED = 'GET_SYS_MSG_DETAIL_BY_SYS_MSG_ID_FAILED';

export default {
    GET_GROUP_BATCH_REQUESTED,
    GET_GROUP_BATCH_SUCCEEDED,
    GET_GROUP_BATCH_FAILED,
    GET_TEACHER_MSG_DETAIL_REQUESTED,
    GET_TEACHER_MSG_DETAIL_SUCCEEDED,
    GET_TEACHER_MSG_DETAIL_FAILED,
    GET_SYS_MSG_DETAIL_BY_SYS_MSG_ID_REQUESTED,
    GET_SYS_MSG_DETAIL_BY_SYS_MSG_ID_SUCCEEDED,
    GET_SYS_MSG_DETAIL_BY_SYS_MSG_ID_FAILED,
}
