/*
** @file: personalProfile(Constants)
** @author: huanghaolei
** @date: 2019-08-19
*/

export const GET_USER_PROFILE_REQUESTED = 'GET_USER_PROFILE_REQUESTED'
export const GET_USER_PROFILE_SUCCEEDED = 'GET_USER_PROFILE_SUCCEEDED'
export const GET_USER_PROFILE_FAILED = 'GET_USER_PROFILE_FAILED'
export const QUERY_TAG_REQUESTED = 'QUERY_TAG_REQUESTED'
export const QUERY_TAG_SUCCEEDED = 'QUERY_TAG_SUCCEEDED'
export const QUERY_TAG_FAILED = 'QUERY_TAG_FAILED'
export const UPDATE_TAG_INFO_REQUESTED = 'UPDATE_TAG_INFO_REQUESTED'
export const UPDATE_TAG_INFO_SUCCEEDED = 'UPDATE_TAG_INFO_SUCCEEDED'
export const UPDATE_TAG_INFO_FAILED = 'UPDATE_TAG_INFO_FAILED'
export const GET_MY_POST_LIST_REQUESTED = 'GET_MY_POST_LIST_REQUESTED'
export const GET_MY_POST_LIST_SUCCEEDED = 'GET_MY_POST_LIST_SUCCEEDED'
export const GET_MY_POST_LIST_FAILED = 'GET_MY_POST_LIST_FAILED'

export const ON_RESET_PERSONAL_PROFILE_STORE = 'ON_RESET_PERSONAL_PROFILE_STORE'

export default {
    GET_USER_PROFILE_REQUESTED,
    GET_USER_PROFILE_SUCCEEDED,
    GET_USER_PROFILE_FAILED,
    QUERY_TAG_REQUESTED,
    QUERY_TAG_SUCCEEDED,
    QUERY_TAG_FAILED,
    UPDATE_TAG_INFO_REQUESTED,
    UPDATE_TAG_INFO_SUCCEEDED,
    UPDATE_TAG_INFO_FAILED,
    GET_MY_POST_LIST_REQUESTED,
    GET_MY_POST_LIST_SUCCEEDED,
    GET_MY_POST_LIST_FAILED,
    ON_RESET_PERSONAL_PROFILE_STORE,
}
