export const GET_POST_DETAIL_REQUESTED = 'GET_POST_DETAIL_REQUESTED';
export const GET_POST_DETAIL_SUCCEEDED = 'GET_POST_DETAIL_SUCCEEDED';
export const GET_POST_DETAIL_FAILED = 'GET_POST_DETAIL_FAILED';
export const GET_PRAISE_USER_LIST_REQUESTED = 'GET_PRAISE_USER_LIST_REQUESTED'
export const GET_PRAISE_USER_LIST_SUCCEEDED = 'GET_PRAISE_USER_LIST_SUCCEEDED'
export const GET_PRAISE_USER_LIST_FAILED = 'GET_PRAISE_USER_LIST_FAILED'

export const ON_RESET_POST_STORE = 'ON_RESET_POST_STORE'

export default {
    GET_POST_DETAIL_REQUESTED,
    GET_POST_DETAIL_SUCCEEDED,
    GET_POST_DETAIL_FAILED,
    GET_PRAISE_USER_LIST_REQUESTED,
    GET_PRAISE_USER_LIST_SUCCEEDED,
    GET_PRAISE_USER_LIST_FAILED,
    ON_RESET_POST_STORE,
}
