export const GET_SUT_DIND_NESS_REQUESTED = 'GET_SUT_DIND_NESS_REQUESTED'
export const GET_SUT_DIND_NESS_SUCCEEDED = 'GET_SUT_DIND_NESS_SUCCEEDED'
export const GET_SUT_DIND_NESS_FAILED = 'GET_SUT_DIND_NESS_FAILED'

export const SAVE_COMMON_INFO = 'SAVE_COMMON_INFO'

// h5 - 爱心捐赠项目列表
export const GET_PROJECT_LIST_REQUESTED = 'GET_PROJECT_LIST_REQUESTED'
export const GET_PROJECT_LIST_SUCCEEDED = 'GET_PROJECT_LIST_SUCCEEDED'
export const GET_PROJECT_LIST_FAILED = 'GET_PROJECT_LIST_FAILED'

// h5 - 我的捐赠排行
export const GET_MY_DONATION_RANK_REQUESTED = 'GET_MY_DONATION_RANK_REQUESTED'
export const GET_MY_DONATION_RANK_SUCCEEDED = 'GET_MY_DONATION_RANK_SUCCEEDED'
export const GET_MY_DONATION_RANK_FAILED = 'GET_MY_DONATION_RANK_FAILED'

// h5 - 捐赠排行榜
export const GET_DONATION_RANK_REQUESTED = 'GET_DONATION_RANK_REQUESTED'
export const GET_DONATION_RANK_SUCCEEDED = 'GET_DONATION_RANK_SUCCEEDED'
export const GET_DONATION_RANK_FAILED = 'GET_DONATION_RANK_FAILED'

// h5 - 兑换爱心
export const EXCHANGE_KINDNESS_REQUESTED = 'EXCHANGE_KINDNESS_REQUESTED'
export const EXCHANGE_KINDNESS_SUCCEEDED = 'EXCHANGE_KINDNESS_SUCCEEDED'
export const EXCHANGE_KINDNESS_FAILED = 'EXCHANGE_KINDNESS_FAILED'

// h5 - 获取公益项目信息 (包含预览)
export const GET_PROJECT_DETAIL_REQUESTED = 'GET_PROJECT_DETAIL_REQUESTED'
export const GET_PROJECT_DETAIL_SUCCEEDED = 'GET_PROJECT_DETAIL_SUCCEEDED'
export const GET_PROJECT_DETAIL_FAILED = 'GET_PROJECT_DETAIL_FAILED'

// h5 - 捐赠爱心
export const DONATE_KINDNESS_REQUESTED = 'DONATE_KINDNESS_REQUESTED'
export const DONATE_KINDNESS_SUCCEEDED = 'DONATE_KINDNESS_SUCCEEDED'
export const DONATE_KINDNESS_FAILED = 'DONATE_KINDNESS_FAILED'

export default {
    GET_SUT_DIND_NESS_REQUESTED,
    GET_SUT_DIND_NESS_SUCCEEDED,
    GET_SUT_DIND_NESS_FAILED,
    SAVE_COMMON_INFO,
    GET_PROJECT_LIST_REQUESTED,
    GET_PROJECT_LIST_SUCCEEDED,
    GET_PROJECT_LIST_FAILED,
    GET_MY_DONATION_RANK_REQUESTED,
    GET_MY_DONATION_RANK_SUCCEEDED,
    GET_MY_DONATION_RANK_FAILED,
    GET_DONATION_RANK_REQUESTED,
    GET_DONATION_RANK_SUCCEEDED,
    GET_DONATION_RANK_FAILED,
    EXCHANGE_KINDNESS_REQUESTED,
    EXCHANGE_KINDNESS_SUCCEEDED,
    EXCHANGE_KINDNESS_FAILED,
    GET_PROJECT_DETAIL_REQUESTED,
    GET_PROJECT_DETAIL_SUCCEEDED,
    GET_PROJECT_DETAIL_FAILED,
    DONATE_KINDNESS_REQUESTED,
    DONATE_KINDNESS_SUCCEEDED,
    DONATE_KINDNESS_FAILED,
}
