export const GET_QUESTION_DETAIL_REQUESTED = 'GET_QUESTION_DETAIL_REQUESTED';
export const GET_QUESTION_DETAIL_SUCCEEDED = 'GET_QUESTION_DETAIL_SUCCEEDED';
export const GET_QUESTION_DETAIL_FAILED = 'GET_QUESTION_DETAIL_FAILED';

export const GET_ANSWER_DETAIL_REQUESTED = 'GET_ANSWER_DETAIL_REQUESTED';
export const GET_ANSWER_DETAIL_SUCCEEDED = 'GET_ANSWER_DETAIL_SUCCEEDED';
export const GET_ANSWER_DETAIL_FAILED = 'GET_ANSWER_DETAIL_FAILED';

export default {
    GET_QUESTION_DETAIL_REQUESTED,
    GET_QUESTION_DETAIL_SUCCEEDED,
    GET_QUESTION_DETAIL_FAILED,
	GET_ANSWER_DETAIL_REQUESTED,
	GET_ANSWER_DETAIL_SUCCEEDED,
	GET_ANSWER_DETAIL_FAILED,
}
