export const GET_WEIXIN_RECORD_LIST_REQUESTED = 'GET_WEIXIN_RECORD_LIST_REQUESTED'
export const GET_WEIXIN_RECORD_LIST_SUCCEEDED = 'GET_WEIXIN_RECORD_LIST_SUCCEEDED'
export const GET_WEIXIN_RECORD_LIST_FAILED = 'GET_WEIXIN_RECORD_LIST_FAILED'
export const ON_CLEAR_RECORD_LIST = 'ON_CLEAR_RECORD_LIST'

export default {
    GET_WEIXIN_RECORD_LIST_REQUESTED,
    GET_WEIXIN_RECORD_LIST_SUCCEEDED,
    GET_WEIXIN_RECORD_LIST_FAILED,
    ON_CLEAR_RECORD_LIST,
}