export const GET_VIDEO_DETAIL_REQUESTED = 'GET_VIDEO_DETAIL_REQUESTED';
export const GET_VIDEO_DETAIL_SUCCEEDED = 'GET_VIDEO_DETAIL_SUCCEEDED';
export const GET_VIDEO_DETAIL_FAILED = 'GET_VIDEO_DETAIL_FAILED';

export const GET_SUGGESTED_VIDEO_LIST_REQUESTED = 'GET_SUGGESTED_VIDEO_LIST_REQUESTED';
export const GET_SUGGESTED_VIDEO_LIST_SUCCEEDED = 'GET_SUGGESTED_VIDEO_LIST_SUCCEEDED';
export const GET_SUGGESTED_VIDEO_LIST_FAILED = 'GET_SUGGESTED_VIDEO_LIST_FAILED';

export const GET_SCHOOL_PAGE_DATA_REQUESTED = 'GET_SCHOOL_PAGE_DATA_REQUESTED';
export const GET_SCHOOL_PAGE_DATA_SUCCEEDED = 'GET_SCHOOL_PAGE_DATA_SUCCEEDED';
export const GET_SCHOOL_PAGE_DATA_FAILED = 'GET_SCHOOL_PAGE_DATA_FAILED';

export default {
    GET_VIDEO_DETAIL_REQUESTED,
    GET_VIDEO_DETAIL_SUCCEEDED,
    GET_VIDEO_DETAIL_FAILED,
    GET_SUGGESTED_VIDEO_LIST_REQUESTED,
    GET_SUGGESTED_VIDEO_LIST_SUCCEEDED,
    GET_SUGGESTED_VIDEO_LIST_FAILED,
    GET_SCHOOL_PAGE_DATA_REQUESTED,
    GET_SCHOOL_PAGE_DATA_SUCCEEDED,
    GET_SCHOOL_PAGE_DATA_FAILED
}
