/*
** @file: constants-sideEffect.js
** @author: huanghaolei
** @date: 2019-06-11
*/


export const GET_PUBLISHED_POST_REQUESTED = 'GET_PUBLISHED_POST_REQUESTED'
export const GET_PUBLISHED_POST_SUCCEEDED = 'GET_PUBLISHED_POST_SUCCEEDED'
export const GET_PUBLISHED_POST_FAILED = 'GET_PUBLISHED_POST_FAILED'
export const GET_USER_INFO_REQUESTED = 'GET_USER_INFO_REQUESTED'
export const GET_USER_INFO_SUCCEEDED = 'GET_USER_INFO_SUCCEEDED'
export const GET_USER_INFO_FAILED = 'GET_USER_INFO_FAILED'
export const ON_CLEAR_SIDE_EFFECT_LIST = 'ON_CLEAR_SIDE_EFFECT_LIST'

export const ON_CLEAR_STORY_SET_DATA = 'ON_CLEAR_STORY_SET_DATA'

export const ON_DO_AUTH_FOR_SKY_NET_REQUESTED = 'ON_DO_AUTH_FOR_SKY_NET_REQUESTED'
export const ON_DO_AUTH_FOR_SKY_NET_SUCCEEDED = 'ON_DO_AUTH_FOR_SKY_NET_SUCCEEDED'
export const ON_DO_AUTH_FOR_SKY_NET_FAILED = 'ON_DO_AUTH_FOR_SKY_NET_FAILED'

export default {
    GET_PUBLISHED_POST_REQUESTED,
    GET_PUBLISHED_POST_SUCCEEDED,
    GET_PUBLISHED_POST_FAILED,
    GET_USER_INFO_REQUESTED,
    GET_USER_INFO_SUCCEEDED,
    GET_USER_INFO_FAILED,
    ON_CLEAR_SIDE_EFFECT_LIST,
    ON_CLEAR_STORY_SET_DATA,
    ON_DO_AUTH_FOR_SKY_NET_REQUESTED,
    ON_DO_AUTH_FOR_SKY_NET_SUCCEEDED,
    ON_DO_AUTH_FOR_SKY_NET_FAILED,
}