//根据话题获取帖子列表
export const GET_POST_BY_SUBJECT_REQUESTED = 'GET_POST_BY_SUBJECT_REQUESTED';
export const GET_POST_BY_SUBJECT_SUCCEEDED = 'GET_POST_BY_SUBJECT_SUCCEEDED';
export const GET_POST_BY_SUBJECT_FAILED = 'GET_POST_BY_SUBJECT_FAILED';

export default {
    GET_POST_BY_SUBJECT_REQUESTED,
    GET_POST_BY_SUBJECT_SUCCEEDED,
    GET_POST_BY_SUBJECT_FAILED
}
