export const GET_PERSON_CENTER_RETRIVE_REQUESTED = 'GET_PERSON_CENTER_RETRIVE_REQUESTED'
export const GET_PERSON_CENTER_RETRIVE_SUCCEEDED = 'GET_PERSON_CENTER_RETRIVE_SUCCEEDED'
export const GET_PERSON_CENTER_RETRIVE_FAILED = 'GET_PERSON_CENTER_RETRIVE_FAILED'
export const GET_RECORD_SWITCHER_MANAGER_REQUESTED = 'GET_RECORD_SWITCHER_MANAGER_REQUESTED'
export const GET_RECORD_SWITCHER_MANAGER_SUCCEEDED = 'GET_RECORD_SWITCHER_MANAGER_SUCCEEDED'
export const GET_RECORD_SWITCHER_MANAGER_FAILED = 'GET_RECORD_SWITCHER_MANAGER_FAILED'

export default {
    GET_PERSON_CENTER_RETRIVE_REQUESTED,
    GET_PERSON_CENTER_RETRIVE_SUCCEEDED,
    GET_PERSON_CENTER_RETRIVE_FAILED,
    GET_RECORD_SWITCHER_MANAGER_REQUESTED,
    GET_RECORD_SWITCHER_MANAGER_SUCCEEDED,
    GET_RECORD_SWITCHER_MANAGER_FAILED,
}