export const ON_PERSON_CENTER_RETRIVE_INFO_REQUESTED = 'ON_PERSON_CENTER_RETRIVE_INFO_REQUESTED'
export const ON_PERSON_CENTER_RETRIVE_INFO_SUCCEEDED = 'ON_PERSON_CENTER_RETRIVE_INFO_SUCCEEDED'
export const ON_PERSON_CENTER_RETRIVE_INFO_FAILED = 'ON_PERSON_CENTER_RETRIVE_INFO_FAILED'

export const ON_UPDATE_PROFILE_REQUESTED = 'ON_UPDATE_PROFILE_REQUESTED'
export const ON_UPDATE_PROFILE_SUCCEEDED = 'ON_UPDATE_PROFILE_SUCCEEDED'
export const ON_UPDATE_PROFILE_FAILED = 'ON_UPDATE_PROFILE_FAILED'

export const ON_CHANGE = 'ON_CHANGE'
export const ON_CLEAR_USER_CENTER_INFO_PARAMS = 'ON_CLEAR_USER_CENTER_INFO_PARAMS'

export default {
    ON_PERSON_CENTER_RETRIVE_INFO_REQUESTED,
    ON_PERSON_CENTER_RETRIVE_INFO_SUCCEEDED,
    ON_PERSON_CENTER_RETRIVE_INFO_FAILED,
    ON_UPDATE_PROFILE_REQUESTED,
    ON_UPDATE_PROFILE_SUCCEEDED,
    ON_UPDATE_PROFILE_FAILED,
    ON_CHANGE,
    ON_CLEAR_USER_CENTER_INFO_PARAMS,
}