export const ON_CHANGE_ACCOUNT = 'ON_CHANGE_ACCOUNT'
export const ON_MANAGE_BIND_263_REQUESTED = 'ON_MANAGE_BIND_263_REQUESTED'
export const ON_MANAGE_BIND_263_SUCCEEDED = 'ON_MANAGE_BIND_263_SUCCEEDED'
export const ON_MANAGE_BIND_263_FAILED = 'ON_MANAGE_BIND_263_FAILED'
export const ON_GET_USER_BY_TICKET_REQUESTED = 'ON_GET_USER_BY_TICKET_REQUESTED'
export const ON_GET_USER_BY_TICKET_SUCCEEDED = 'ON_GET_USER_BY_TICKET_SUCCEEDED'
export const ON_GET_USER_BY_TICKET_FAILED = 'ON_GET_USER_BY_TICKET_FAILED'
export const ON_CLEAR_PARAMS = 'ON_CLEAR_PARAMS'
export const ON_SAVE_DATA_FROM_URL = 'ON_SAVE_DATA_FROM_URL'

export default {
    ON_CHANGE_ACCOUNT,
    ON_MANAGE_BIND_263_REQUESTED,
    ON_MANAGE_BIND_263_SUCCEEDED,
    ON_MANAGE_BIND_263_FAILED,
    ON_GET_USER_BY_TICKET_REQUESTED,
    ON_GET_USER_BY_TICKET_SUCCEEDED,
    ON_GET_USER_BY_TICKET_FAILED,
    ON_CLEAR_PARAMS,
    ON_SAVE_DATA_FROM_URL,
}
