/*
* @file: filter select options
* @author: huanghaolei
* @date: 2018-09-17
* */

export default {
    provinceList: [{
        label: '北京市',
        value: '北京市',
    }, {
        label: '天津市',
        value: '天津市',
    }, {
        label: '上海市',
        value: '上海市',
    }, {
        label: '重庆市',
        value: '重庆市',
    }, {
        label: '河北省',
        value: '河北省',
    }, {
        label: '山西省',
        value: '山西省',
    }, {
        label: '辽宁省',
        value: '辽宁省',
    }, {
        label: '吉林省',
        value: '吉林省',
    }, {
        label: '黑龙江省',
        value: '黑龙江省',
    }, {
        label: '江苏省',
        value: '江苏省',
    }, {
        label: '浙江省',
        value: '浙江省',
    }, {
        label: '安徽省',
        value: '安徽省',
    }, {
        label: '福建省',
        value: '福建省',
    }, {
        label: '江西省',
        value: '江西省',
    }, {
        label: '山东省',
        value: '山东省',
    }, {
        label: '河南省',
        value: '河南省',
    }, {
        label: '湖北省',
        value: '湖北省',
    }, {
        label: '湖南省',
        value: '湖南省',
    }, {
        label: '广东省',
        value: '广东省',
    }, {
        label: '海南省',
        value: '海南省',
    }, {
        label: '四川省',
        value: '四川省',
    }, {
        label: '贵州省',
        value: '贵州省',
    }, {
        label: '云南省',
        value: '云南省',
    }, {
        label: '陕西省',
        value: '陕西省',
    }, {
        label: '甘肃省',
        value: '甘肃省',
    }, {
        label: '青海省',
        value: '青海省',
    }, {
        label: '内蒙古',
        value: '内蒙古',
    }, {
        label: '广西省',
        value: '广西省',
    }, {
        label: '西藏',
        value: '西藏',
    }, {
        label: '宁夏',
        value: '宁夏',
    }, {
        label: '新疆',
        value: '新疆',
    }, {
        label: '香港',
        value: '香港',
    }, {
        label: '澳门',
        value: '澳门',
    }],
    academyList: [{
        label: 'π学院',
        value: 'π学院',
    }, {
        label: '狐逻&泰罗学院',
        value: '狐逻&泰罗学院',
    }, {
        label: '芒格学院',
        value: '芒格学院',
    }, {
        label: '睿博学院',
        value: '睿博学院',
    }, {
        label: '自变量学院',
        value: '自变量学院',
    }, {
        label: '其他',
        value: '其他',
    }],
    originalEduLevelList: ['待定', '小学', '初中', '高中', '中专', '大专', '本科及以上'],
    sexList: [{
        label: '男',
        value: '男',
    }, {
        label: '女',
        value: '女',
    }],
    ageList: [{
        label: '15~20',
        value: '15~20',
    }, {
        label: '21~25',
        value: '21~25',
    }, {
        label: '26~30',
        value: '26~30',
    }, {
        label: '31~35',
        value: '31~35',
    }, {
        label: '36~40',
        value: '36~40',
    }, {
        label: '40以上',
        value: '40以上',
    }],
    careerList: ['待定', '宝妈', '学生', 'IT白领', 'HR白领', '会计白领', '教师白领', '行政白领', '其他白领', '职场新人', '管理者', '销售', '微商', '工人', '无业'],
    identityLabelList: [{
        label: '宝妈',
        value: '宝妈',
    }, {
        label: '农村户口',
        value: '农村户口',
    }, {
        label: '服务行业',
        value: '服务行业',
    }, {
        label: '退伍军人',
        value: '退伍军人',
    }, {
        label: '大龄考生',
        value: '大龄考生',
    }, {
        label: '成功女性',
        value: '成功女性',
    }, {
        label: '名企高管',
        value: '名企高管',
    }, {
        label: '业界大牛',
        value: '业界大牛',
    }, {
        label: '高分学霸',
        value: '高分学霸',
    }, {
        label: '家庭主妇',
        value: '家庭主妇',
    }],
    contentLabelList: [{
        label: '学习成果类',
        value: '学习成果类',
    }, {
        label: '学员访谈类',
        value: '学员访谈类',
    }, {
        label: '学习方法类',
        value: '学习方法类',
    }, {
        label: '名师专访类',
        value: '名师专访类',
    }, {
        label: '师生故事类',
        value: '师生故事类',
    }, {
        label: '自考励志类',
        value: '自考励志类',
    }, {
        label: '自考资讯类',
        value: '自考资讯类',
    }, {
        label: '自考科普类',
        value: '自考科普类',
    }, {
        label: '晨读好文',
        value: '晨读好文',
    }],
    postSourceList: [{
        label: 'PGC',
        value: 'PGC',
    }, {
        label: 'UGC',
        value: 'UGC',
    }, {
        label: '媒体号',
        value: '媒体号',
    }],
    publishStateList: [{
        label: '未发布',
        value: 0,
    }, {
        label: '已发布',
        value: 1,
    }],
    filterFields: ['province', 'academy', 'majorName', 'education', 'sex', 'age', 'startTime', 'endTime', 'postId', 'studentName',
        'studentId', 'career', 'contentLabel', 'postSource', 'publishState'],
    productTypeList: [{ label: '自考', value: 1 }, { label: '考研', value: 2 }, { label: '资格证', value: 3 }, { label: '其他', value: 0 }],
}
