//我的会议室预定列表
export const MYROOM_SUMMARY_REQUESTED = 'MYROOM_SUMMARY_REQUESTED';
export const MYROOM_SUMMARY_SUCCEEDED = 'MYROOM_SUMMARY_SUCCEEDED';
export const MYROOM_SUMMARY_FAILED = 'MYROOM_SUMMARY_FAILED';

//撤销我的会议室预定
export const MYROOM_DELETE_REQUESTED = 'MYROOM_DELETE_REQUESTED';
export const MYROOM_DELETE_SUCCEEDED = 'MYROOM_DELETE_SUCCEEDED';
export const MYROOM_DELETE_FAILED = 'MYROOM_DELETE_FAILED';

export default {
    MYROOM_SUMMARY_REQUESTED,
    MYROOM_SUMMARY_SUCCEEDED,
    MYROOM_SUMMARY_FAILED,
    MYROOM_DELETE_REQUESTED,
    MYROOM_DELETE_SUCCEEDED,
    MYROOM_DELETE_FAILED
}
